sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tAeHQWTukHHuCtKZ9fT
    access-key-secret: 1P7hNVbuA4k1cVLKCA8S4ljA6YDyCa
    bucket-name: wzq-sky-take-out
  redis:
      host: localhost
      port: 6379
      password:
      database: 0
  wechat:
    appid: wx869f5489e76e76fe
    secret: 336f310ec5c32c5ea8920e7b4e579b6e





